apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-app
  labels:
    app: playground
spec:
  replicas: 3
  selector:
    matchLabels:
      app: playground
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
      - name: playground
        image: rubenernst/kubernetes-playground:1.0.2
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "500Mi"
          requests:
            memory: "375Mi"
        livenessProbe:
          httpGet:
            path: actuator/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 5